name: Windows Build

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

permissions:
  contents: write  # Permite a criação de releases
  id-token: write  # Permite acesso ao GitHub ID token

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flet Build Windows
      run: |
        flutter config --no-analytics
        flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

    - name: Verify build output and list contents of build/windows
      run: |
        if (Test-Path "build/windows") {
          Write-Host "Directory exists, listing contents:"
          Get-ChildItem -Path "build/windows"
        } else {
          Write-Host "Directory does not exist"
        }

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: error
        overwrite: false

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if tag already exists
        id: check_tag
        run: |
          git fetch --tags
          TAG_EXISTS=$(git tag -l "v${{ env.BUILD_VERSION }}")
          echo "Tag exists: $TAG_EXISTS"
          if [ -n "$TAG_EXISTS" ]; then
            echo "Tag v${{ env.BUILD_VERSION }} already exists. Creating a new tag."
            echo "NEW_TAG=v${{ env.BUILD_VERSION }}-${{ github.run_number }}" >> $GITHUB_ENV
          else
            echo "NEW_TAG=v${{ env.BUILD_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body: "Release notes for version ${{ env.NEW_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
      - name: Upload Windows Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/windows/*
          asset_name: windows-build-artifact.zip
          asset_content_type: application/zip
